#include <stdio.h>
#include <stdlib.h>

#define N 20


int main ()
{
	// init rand() seed
	srand (time (NULL));

	// variables
	double data[N]; 

	// self-feeding random data generated by rand()
	printf ("No data is provided, self-feeding random data generated by rand()...\n");
	for (int i = 0; i < N; i++)
		data[i] = (rand()%100000)/100.0;

	
	// calculating the mean
	double mean = 0;
	for(int i = 0; i < N; i++)
		mean+=data[i];
	mean = mean / N;

	// calculating the std
	double variance = 0;
	for (int i = 0; i < N; i++)
		variance += (data[i]-mean)*(data[i]-mean);
	double standard_deviation = sqrt(variance/N)

	
	// OUTPUT
	printf ("We have mean = %lf, standard deviation = %lf\n", mean, standard_deviation);



	return 0;	
}
