#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

#define N 20


int main ()
{
	// init rand() seed
	srand (time (NULL));

	// variables
	int data[N]; 

	// self-feeding random data generated by rand()
	printf ("No data is provided, self-feeding random data generated by rand()...\n");
	int line_count = 1;
	for (int i = 0; i < N; i++) {
		if (line_count % 6 == 0) {
			line_count = 1;
			printf ("\n");
		}
		data[i] = rand() % 10000;
		printf ("%6d ", data[i]);
	}
	printf ("\n");

	
	// calculating the mean
	double mean = 0;
	for(int i = 0; i < N; i++)
		mean+=data[i];
	mean = mean / N;

	// calculating the std
	double variance = 0;
	for (int i = 0; i < N; i++)
		variance += (data[i]-mean)*(data[i]-mean);
	double standard_deviation = sqrt(variance/N);

	
	// OUTPUT
	printf ("We have mean = %lf, standard deviation = %lf\n", mean, standard_deviation);



	return 0;	
}
