build:
	gcc final-01.c -o final-01
	./final-01
	gcc final-02.c -o final-02
	./final-02
	gcc final-03.c -o final-03
	./final-03
	gcc final-04.c -o final-04
	./final-04
	gcc final-05.c -o final-05
	./final-05

